// Electron main.cjs script generators — standard (WebSocket) and client modes

import {
  type AioMeta,
  tmplBounds,
  tmplBoundsTracking,
  tmplKeyboardShortcuts,
  tmplWillNavigate,
  toSlug,
} from "./electron-shared.ts";

/** Generates a minimal Electron main.cjs that loads the given URL */
export function electronMainScript(url: string, meta?: AioMeta): string {
  const w = meta?.width ?? 800;
  const h = meta?.height ?? 600;
  const slug = toSlug(meta?.title ?? "aio-app");
  return `
const { app, BrowserWindow, Menu } = require('electron');
const path = require('path');
const fs = require('fs');
Menu.setApplicationMenu(null);
app.name = ${JSON.stringify(slug)};

// ── Window state persistence ──
${tmplBounds()}

app.on('ready', () => {
  const b = loadBounds(${w}, ${h});
  b.webPreferences = { nodeIntegration: false, contextIsolation: true };
  const win = new BrowserWindow(b);
  if (b.x == null) win.center();
${tmplBoundsTracking()}
  win.loadURL(${JSON.stringify(url)});
  const _appOrigin = new URL(${JSON.stringify(url)}).origin;
${tmplWillNavigate("_appOrigin")}
  // Accept self-signed localhost certs (auto-generated by aio --expose)
  app.on('certificate-error', (event, _wc, _url, _err, _cert, cb) => {
    const u = new URL(${JSON.stringify(url)});
    if (u.hostname === 'localhost' || u.hostname === '127.0.0.1') { event.preventDefault(); cb(true); }
    else cb(false);
  });
${tmplKeyboardShortcuts()}
});
app.on('window-all-closed', () => process.exit(0));
`.trim();
}
