// aiol reads a cell's config the way `am pin` does (h8 F2, F9, F12):
//  • an app STATE key spelled like a removed `aio.run()`/cell option
//    (`listensTo: [...]`, `killExisting`, `every … backoff`, `appVersion`)
//    is app data, not an error;
//  • braces are counted on CODE (a `"{"` value is not a brace) and a config
//    bound to a name (`cell("c", config)`, `{ ...base }`) is followed — the
//    removed key it carries is found, and the cell is not "stateless";
//  • `am testgen`'s AUTO-GENERATED output is not an "unreviewed helper".
import { assertEquals } from "@std/assert";
import { join } from "@std/path";
import { buildContext } from "../aiol/context.ts";
import { checkAlpha52, checkCells, checkScanCoverage } from "../aiol/checks.ts";
import type { Checker } from "../aiol/types.ts";
import { dropTempDir, tempDir } from "../src/testing/temp-dir.ts";

async function lint(
  files: Record<string, string>,
  checks: Checker[],
): Promise<string[]> {
  const dir = await tempDir("aiol-cfg-sites-");
  try {
    await Deno.writeTextFile(
      join(dir, "deno.json"),
      JSON.stringify({ imports: { aio: "jsr:@riagentic/aio@1.0.0" } }),
    );
    for (const [rel, body] of Object.entries(files)) {
      await Deno.mkdir(join(dir, rel, ".."), { recursive: true });
      await Deno.writeTextFile(join(dir, rel), body);
    }
    const { ctx, report } = await buildContext(dir);
    for (const c of checks) await c(ctx);
    return report.issues.map((i) => `${i.severity}: ${i.message}`);
  } finally {
    await dropTempDir(dir);
  }
}

const removedOrStateless = (issues: string[]) =>
  issues.filter((i) => /was removed in|has no state|has no methods/.test(i));

Deno.test("aiol: app state keys spelled like removed aio.run()/cell options are not errors (h8 F2)", async () => {
  const issues = await lint({
    "src/cell.ts": `import { cell } from "aio";
export const c = cell("c", {
  state: {
    listensTo: ["a"],
    retry: { every: 1000, backoff: 2 },
    killExisting: false,
    appVersion: "0.1",
    theme: { ui: "dark" },
  },
  methods: { inc(s) { s.killExisting = true; } },
});
`,
  }, [checkCells, checkAlpha52]);
  assertEquals(removedOrStateless(issues), []);
});

Deno.test("aiol: a cell's OWN listensTo array still errors, once (h8 F2 control)", async () => {
  const issues = await lint({
    "src/cell.ts": `import { cell } from "aio";
export const c = cell("c", {
  state: { n: 0 },
  listensTo: ["other"],
  methods: { inc(s) { s.n++; } },
});
`,
  }, [checkCells, checkAlpha52]);
  assertEquals(
    removedOrStateless(issues).filter((i) => i.includes("listensTo")).length,
    1,
    JSON.stringify(issues),
  );
});

Deno.test("aiol: a brace inside a state string does not hide state or methods (h8 F9)", async () => {
  const issues = await lint({
    "src/cell.ts": `import { cell } from "aio";
export const c = cell("c", {
  state: { n: 0, open: "{" },
  methods: { inc(s) { s.n++; } },
});
`,
  }, [checkCells]);
  assertEquals(removedOrStateless(issues), []);
});

Deno.test("aiol: a config bound to a name is followed — its removed key is found, its state is seen (h8 F9)", async () => {
  const issues = await lint({
    "src/cell.ts": `import { cell } from "aio";
const config = {
  state: { n: 0 },
  methods: { inc(s: { n: number }) { s.n++; } },
  machine: { initial: "idle" },
};
export const c = cell("c", config);
`,
  }, [checkCells]);
  assertEquals(
    removedOrStateless(issues).map((i) => /'(\w+):'|has no \w+/.exec(i)?.[0]),
    ["'machine:'"],
  );
  const spread = await lint({
    "src/cell.ts": `import { cell } from "aio";
const base = { actions: { inc: {} } };
export const c = cell("c", { ...base, state: { n: 0 }, methods: { go() {} } });
`,
  }, [checkCells]);
  assertEquals(
    removedOrStateless(spread).map((i) => /'(\w+):'|has no \w+/.exec(i)?.[0]),
    ["'actions:'"],
  );
});

Deno.test("aiol: a quoted removed key and a generic cell<…>( are still read (h8 F9/F10)", async () => {
  const issues = await lint({
    "src/cell.ts": `import { cell } from "aio";
type S = { n: number };
export const c = cell<S>("c", {
  state: { n: 0 },
  methods: { inc(s) { s.n++; } },
  "machine": { initial: "idle" },
});
`,
  }, [checkCells]);
  assertEquals(
    removedOrStateless(issues).map((i) => /'(\w+):'|has no \w+/.exec(i)?.[0]),
    ["'machine:'"],
  );
});

Deno.test("aiol: am testgen's AUTO-GENERATED client is not an unreviewed helper (h8 F12)", async () => {
  const hint = (issues: string[]) =>
    issues.filter((i) => i.includes("helpers, not tests"));
  const gen = await lint({
    "src/cell.ts": `import { cell } from "aio";
export const c = cell("c", { state: { n: 0 }, methods: { inc(s) { s.n++; } } });
`,
    "tests/ui.gen.ts":
      "// AUTO-GENERATED by am testgen — do not edit\nexport const ui = {};\n",
  }, [checkScanCoverage]);
  assertEquals(hint(gen), []);
  // Control: a hand-written helper is still named.
  const hand = await lint({
    "src/cell.ts": `import { cell } from "aio";
export const c = cell("c", { state: { n: 0 }, methods: { inc(s) { s.n++; } } });
`,
    "tests/helpers.ts": "export const token = 'x';\n",
  }, [checkScanCoverage]);
  assertEquals(hint(hand).length, 1);
});
