// `am testgen` output: per-INSTANCE members, and the header aiol skips.
//
// Four `<Button>`s under `<App>` were merged into ONE typed member,
// `Button: { apply, pause, reset, start }` — a shape no single instance has,
// while the runtime addresses them as `Button` (the first), `Button2`, … (h3
// F9). And the file tripped `deno task lint` on every run ("helpers, not
// tests … unreviewed"), because nothing marked it generated.
//
// The proof is the RUNTIME: every member the generator emits is resolved on a
// live `testUI` handle, and each instance's elements are found on the
// instance the member names.
import { assert, assertEquals, assertStringIncludes } from "@std/assert";
import { testUI } from "../src/testing/ui-test.ts";
import { generateUITypes } from "../src/testing/ui-testgen.ts";
import {
  childCoverageDir,
  dropTempDir,
  tempDir,
} from "../src/testing/temp-dir.ts";

function Button(props: { t?: string; children: string }) {
  return <button type="button" t={props.t}>{props.children}</button>;
}

function Card(props: { title: string }) {
  return (
    <div>
      <button type="button">Open {props.title}</button>
    </div>
  );
}

function App() {
  return (
    <div>
      <Button t="start">Start</Button>
      <Button t="pause">Pause</Button>
      <Button t="reset">Reset</Button>
      <Button t="apply">Apply</Button>
      <Card title="A" />
    </div>
  );
}

/** `readonly <name>: <Type>;` members of one emitted interface. */
function members(src: string, iface: string): Map<string, string> {
  const body = new RegExp(
    `export interface ${iface} extends UIComponentHandle \\{([^}]*)\\}`,
  ).exec(src)?.[1] ?? "";
  return new Map(
    [...body.matchAll(/readonly ("?[\w$-]+"?): ([^;]+);/g)].map((m) => [
      m[1]!.replaceAll('"', ""),
      m[2]!,
    ]),
  );
}

Deno.test("testgen: the first line is the marker aiol skips", async () => {
  await using ui = await testUI(App);
  await ui.settle();
  const src = generateUITypes(ui.surface());
  assertEquals(
    src.split("\n")[0],
    "// AUTO-GENERATED by am testgen — do not edit",
  );
});

Deno.test("testgen: one member per INSTANCE, spelled the way the runtime resolves it", async () => {
  await using ui = await testUI(App);
  await ui.settle();
  const src = generateUITypes(ui.surface());
  const app = members(src, "AppUI");
  for (const name of ["Button", "Button2", "Button3", "Button4"]) {
    assert(app.has(name), `AppUI lacks ${name}:\n${src}`);
  }
  // Each instance is typed with ITS OWN elements — never the union.
  const types = ["Button", "Button2", "Button3", "Button4"].map((n) =>
    app.get(n)!.split(" & ")[0]!
  );
  const expected = ["start", "pause", "reset", "apply"];
  types.forEach((t, i) => {
    const els = [...members(src, t).keys()];
    assertEquals(els, [expected[i]!], `${t} carries only its own element`);
  });
  // The runtime agrees, member by member.
  // deno-lint-ignore no-explicit-any
  const App_ = (ui as any).App;
  ["Button", "Button2", "Button3", "Button4"].forEach((n, i) => {
    // deno-lint-ignore no-explicit-any
    const el = (App_[n] as any)[expected[i]!];
    assertEquals(
      el.text,
      expected[i]![0]!.toUpperCase() + expected[i]!.slice(1),
    );
  });
  // A single instance keeps its bare name.
  assert(app.has("Card"), src);
  assert(!app.has("Card2"), src);
});

Deno.test("testgen: the emitted module type-checks", async () => {
  await using ui = await testUI(App);
  await ui.settle();
  const src = generateUITypes(ui.surface(), {
    importFrom: new URL("../src/cell-test.ts", import.meta.url).href,
  });
  assertStringIncludes(src, "export type TypedTestUI");
  const dir = await tempDir("testgen-instances-");
  const tmp = `${dir}/ui.gen.ts`;
  try {
    await Deno.writeTextFile(tmp, src);
    const out = await new Deno.Command(Deno.execPath(), {
      env: { DENO_COVERAGE_DIR: childCoverageDir() },
      args: ["check", "--no-lock", tmp],
      stdout: "null",
      stderr: "piped",
    }).output();
    assertEquals(
      out.code,
      0,
      `generated types failed deno check:\n${
        new TextDecoder().decode(out.stderr)
      }\n${src}`,
    );
  } finally {
    await dropTempDir(dir);
  }
});
