// ui-testgen.ts — generate fully-typed UI-test clients from the live semantic
// surface. Types come from what actually RENDERS (not from parsing TSX), so
// `ui.App.SubmitButton.click()` autocompletes and a renamed button breaks
// tests at compile time. Spec: docs/specs/2026-07-10-semantic-ui-testing.md §5.

import type { ComponentFn } from "../air/vdom.ts";
import type { UISurfaceNode } from "../air/ui-surface.ts";
import { testUI, type TestUIOptions } from "./ui-test.ts";

/** Valid TS identifier → bare key; anything else → quoted key. */
function key(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

/** PascalCase a component name into a safe interface name. */
function ifaceName(component: string, taken: Set<string>): string {
  let base = component.replace(/[^A-Za-z0-9_$]/g, "") || "Component";
  if (!/^[A-Za-z_$]/.test(base)) base = "C" + base;
  let name = `${base}UI`;
  let i = 2;
  while (taken.has(name)) name = `${base}UI${i++}`;
  taken.add(name);
  return name;
}

/** Merge element/child names across all instances of the same component name
 *  (keyed rows render the same component many times — the type is the union). */
function collect(
  node: UISurfaceNode,
  acc: Map<string, { elements: Set<string>; children: Set<string> }>,
): void {
  let entry = acc.get(node.component);
  if (!entry) {
    entry = { elements: new Set(), children: new Set() };
    acc.set(node.component, entry);
  }
  for (const el of node.elements) entry.elements.add(el.name);
  for (const child of node.children) {
    entry.children.add(child.component);
    collect(child, acc);
  }
}

/**
 * Generate TypeScript source for a fully-typed test client from a semantic
 * surface. Pure — pass any {@linkcode UISurfaceNode} (from `ui.surface()` or a
 * live client's `am surface --json`).
 *
 * The generated module exports one interface per component plus
 * `TypedTestUI` — intersect it with the `testUI` result:
 *
 * ```ts
 * const ui = await testUI(App, { document }) as TypedTestUI;
 * await ui.App.SubmitButton.click(); // autocompleted, compile-checked
 * ```
 */
export function generateUITypes(
  root: UISurfaceNode,
  opts: { importFrom?: string } = {},
): string {
  const from = opts.importFrom ?? "aio/testing";
  const acc = new Map<
    string,
    { elements: Set<string>; children: Set<string> }
  >();
  collect(root, acc);

  const taken = new Set<string>();
  const names = new Map<string, string>(); // component → interface name
  for (const component of acc.keys()) {
    names.set(component, ifaceName(component, taken));
  }

  const lines: string[] = [
    "// AUTO-GENERATED by aio testgen — regenerate after UI changes; do not edit.",
    `import type {`,
    `  TestUI,`,
    `  UIComponentHandle,`,
    `  UIElementHandle,`,
    `} from "${from}";`,
    "",
  ];
  for (const [component, entry] of acc) {
    const iface = names.get(component)!;
    lines.push(`/** Typed surface of <${component}> */`);
    lines.push(`export interface ${iface} extends UIComponentHandle {`);
    for (const el of [...entry.elements].sort()) {
      lines.push(`  readonly ${key(el)}: UIElementHandle;`);
    }
    for (const child of [...entry.children].sort()) {
      lines.push(`  readonly ${key(child)}: ${names.get(child)};`);
    }
    lines.push("}");
    lines.push("");
  }
  const rootIface = names.get(root.component)!;
  lines.push(
    `/** Intersect with the testUI result for full typing:`,
    ` *  \`const ui = await testUI(App, opts) as TypedTestUI;\` */`,
    `export type TypedTestUI = TestUI & {`,
    `  readonly ${key(root.component)}: ${rootIface};`,
    `};`,
    "",
  );
  return lines.join("\n");
}

/**
 * Convenience: mount an app in-process (happy-dom via `opts.document`), walk
 * its surface, and return the generated typed-client source. Write it to a
 * file in a tiny project script:
 *
 * ```ts
 * // scripts/testgen.ts (in your app)
 * import { Window } from "happy-dom";
 * import { testGen } from "aio/testing";
 * import App from "../src/App.tsx";
 * import { todo } from "../src/cell/todo.ts";
 *
 * const src = await testGen(App, {
 *   document: new Window().document,
 *   cells: [todo],
 * });
 * await Deno.writeTextFile("tests/ui.gen.ts", src);
 * ```
 */
export async function testGen(
  App: ComponentFn,
  opts: TestUIOptions & { importFrom?: string } = {},
): Promise<string> {
  const ui = await testUI(App, opts);
  try {
    return generateUITypes(ui.surface(), { importFrom: opts.importFrom });
  } finally {
    ui.unmount();
  }
}

/** @deprecated alpha52 — renamed {@linkcode testGen} (camelCase, matching
 *  testUI/testCell). Alias through beta. */
export const testgen = testGen;
