// ui-testgen.ts — generate fully-typed UI-test clients from the live semantic
// surface. Types come from what actually RENDERS (not from parsing TSX), so
// `ui.App.SubmitButton.click()` autocompletes and a renamed button breaks
// tests at compile time. Spec: docs/specs/2026-07-10-semantic-ui-testing.md §5.

import type { ComponentFn } from "../air/vdom.ts";
import type { UISurfaceNode } from "../air/ui-surface.ts";
import { findComponents, findElementsDeep } from "../air/ui-surface.ts";
import { testUI, type TestUIOptions } from "./ui-test.ts";

/** Valid TS identifier → bare key; anything else → quoted key. */
function key(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

/** PascalCase a component name into a safe interface name. */
function ifaceName(component: string, taken: Set<string>): string {
  let base = component.replace(/[^A-Za-z0-9_$]/g, "") || "Component";
  if (!/^[A-Za-z_$]/.test(base)) base = "C" + base;
  let name = `${base}UI`;
  let i = 2;
  while (taken.has(name)) name = `${base}UI${i++}`;
  taken.add(name);
  return name;
}

/** The first line of every generated client — the marker aiol recognises
 *  as "generated, not a helper to review" (h3 F9). Exact text; do not reword. */
export const TESTGEN_MARKER = "// AUTO-GENERATED by am testgen — do not edit";

/** A node's members as the RUNTIME resolves them from a handle on it.
 *
 *  `ui.App.Button` is the FIRST `Button` in depth-first order, `Button2`… the
 *  later ones (`ordinalComponent` / `oneComponent` in ui-test.ts), and a `t`
 *  handle on a component is an alias for it. Instances used to be merged into
 *  one member typed with the UNION of their elements — four buttons became
 *  `Button: { apply, pause, reset, start }`, a shape no instance has, and
 *  `Button2` had no type at all. */
function nodeMembers(
  node: UISurfaceNode,
): { elements: string[]; children: [string, UISurfaceNode, boolean][] } {
  const elements = [...new Set(node.elements.map((e) => e.name))].sort();
  const taken = new Set(elements);
  const children: [string, UISurfaceNode, boolean][] = [];
  const add = (name: string, n: UISurfaceNode, alsoElement = false) => {
    // An exact name always wins at runtime, so an ordinal that collides with
    // one is not what the runtime would hand back — leave it out.
    if (taken.has(name)) return;
    taken.add(name);
    children.push([name, n, alsoElement]);
  };
  const names = [...new Set(node.children.map((c) => c.component))];
  for (const name of names) {
    const hits = findComponents(node, name);
    hits.forEach((hit, i) => add(i === 0 ? name : `${name}${i + 1}`, hit));
  }
  for (const c of node.children) {
    const h = c.handle;
    if (!h || findComponents(node, h).length !== 1) continue;
    // A handle the component FORWARDS to an element it renders names both —
    // the runtime hands back a component that also acts as that element.
    add(h, c, findElementsDeep(c, h).length > 0);
  }
  children.sort((a, b) => a[0].localeCompare(b[0]));
  return { elements, children };
}

/**
 * Generate TypeScript source for a fully-typed test client from a semantic
 * surface. Pure — pass any {@linkcode UISurfaceNode} (from `ui.surface()` or a
 * live client's `am surface --json`).
 *
 * The generated module exports one interface per distinct component SHAPE
 * (instances that render the same members share one) plus `TypedTestUI` —
 * intersect it with the `testUI` result:
 *
 * ```ts
 * const ui = await testUI(App, { document }) as TypedTestUI;
 * await ui.App.SubmitButton.click(); // autocompleted, compile-checked
 * await ui.App.Button2.start.click(); // the 2nd <Button>, its own elements
 * ```
 */
export function generateUITypes(
  root: UISurfaceNode,
  opts: { importFrom?: string } = {},
): string {
  const from = opts.importFrom ?? "aio/testing";
  const taken = new Set<string>();
  /** structural signature → interface name */
  const bySig = new Map<string, string>();
  const bodies: string[] = [];

  // Post-order: a node's interface is emitted after its children's, and two
  // instances with the same members (keyed rows) share one interface.
  const visit = (node: UISurfaceNode): string => {
    const m = nodeMembers(node);
    const childTypes = m.children.map(([name, n, alsoEl]) => {
      const t = visit(n);
      return [name, alsoEl ? `${t} & UIElementHandle` : t] as const;
    });
    const sig = JSON.stringify([node.component, m.elements, childTypes]);
    const known = bySig.get(sig);
    if (known) return known;
    const iface = ifaceName(node.component, taken);
    bySig.set(sig, iface);
    const lines = [
      `/** Typed surface of <${node.component}> */`,
      `export interface ${iface} extends UIComponentHandle {`,
    ];
    for (const el of m.elements) {
      lines.push(`  readonly ${key(el)}: UIElementHandle;`);
    }
    for (const [name, t] of childTypes) {
      lines.push(`  readonly ${key(name)}: ${t};`);
    }
    lines.push("}", "");
    bodies.push(lines.join("\n"));
    return iface;
  };
  const rootIface = visit(root);

  return [
    TESTGEN_MARKER,
    "// Regenerate after UI changes: `am testgen`.",
    `import type {`,
    `  TestUI,`,
    `  UIComponentHandle,`,
    `  UIElementHandle,`,
    `} from "${from}";`,
    "",
    ...bodies,
    `/** Intersect with the testUI result for full typing:`,
    ` *  \`const ui = await testUI(App, opts) as TypedTestUI;\` */`,
    `export type TypedTestUI = TestUI & {`,
    `  readonly ${key(root.component)}: ${rootIface};`,
    `};`,
    "",
  ].join("\n");
}

/**
 * Convenience: mount an app in-process (happy-dom via `opts.document`), walk
 * its surface, and return the generated typed-client source. Write it to a
 * file in a tiny project script:
 *
 * ```ts
 * // scripts/testgen.ts (in your app)
 * import { Window } from "happy-dom";
 * import { testGen } from "aio/testing";
 * import App from "../src/App.tsx";
 * import { todo } from "../src/cell/todo.ts";
 *
 * const src = await testGen(App, {
 *   document: new Window().document,
 *   cells: [todo],
 * });
 * await Deno.writeTextFile("tests/ui.gen.ts", src);
 * ```
 */
export async function testGen(
  App: ComponentFn,
  opts: TestUIOptions & { importFrom?: string } = {},
): Promise<string> {
  const ui = await testUI(App, opts);
  try {
    return generateUITypes(ui.surface(), { importFrom: opts.importFrom });
  } finally {
    ui.unmount();
  }
}
