// Electron script generation helpers — typed wrappers around string templates
// Phase 1: Extract helpers, add version guards, improve debuggability
// Phase 2+: Move to .cjs files in src/electron/scripts/

/** Slugifies a title for use as Electron app name (stable userData path) */
export function toSlug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") ||
    "aio-app";
}

/** Safely escapes a URL for embedding in executeJavaScript string.
 *  Handles backslashes and single quotes to prevent injection. */
export function escapeForExecuteJavaScript(url: string): string {
  return url.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

/** Checks Electron version constraints.
 *  Throws if the running Electron version doesn't meet minimum requirements. */
export function requireElectronVersion(minMajor: number, minMinor = 0): void {
  const proc = globalThis as unknown as {
    process?: { versions?: { electron?: string } };
  };
  const v = proc.process?.versions?.electron;
  if (!v) return; // Not running in Electron
  const [major, minor] = v.split(".").map(Number);
  if (major === undefined || isNaN(major)) return;
  if (major < minMajor || (major === minMajor && (minor ?? 0) < minMinor)) {
    throw new Error(
      `Electron ${v} does not meet minimum requirement ${minMajor}.${minMinor}. ` +
        `Upgrade Electron or use a lower API target.`,
    );
  }
}

/** Typed window metadata for Electron launch */
export interface ElectronWindowMeta {
  title?: string;
  width?: number;
  height?: number;
}

/** Builds the will-navigate handler code with proper URL validation.
 *  Returns a typed string for use in Electron main script template. */
export function buildWillNavigateHandler(appOrigin: string): string {
  return `
  const _appOrigin = ${JSON.stringify(appOrigin)};
  win.webContents.on('will-navigate', (event, navUrl) => {
    try {
      const u = new URL(navUrl);
      if (u.origin === _appOrigin && (u.pathname === '/' || u.pathname === '')) return;
    } catch {}
    event.preventDefault();
    const escaped = '${/* will be replaced at runtime */ ""}'.replace(/\\\\/g, '\\\\\\\\').replace(/'/g, "\\\\'");
    win.webContents.executeJavaScript(
      "window.dispatchEvent(new CustomEvent('aio:navigate',{detail:{url:'" + escaped + "'}}))"
    ).catch(() => {});
  });`.trim();
}

/** Builds certificate-error handler for self-signed localhost certs.
 *  Only accepts localhost/127.0.0.1 in development. */
export function buildCertificateHandler(appUrl: string): string {
  const u = new URL(appUrl);
  const isLocalhost = u.hostname === "localhost" || u.hostname === "127.0.0.1";
  if (!isLocalhost) return "";
  return `
  // Accept self-signed localhost certs (auto-generated by aio --expose)
  app.on('certificate-error', (event, _wc, _url, _err, _cert, cb) => {
    const u = new URL(${JSON.stringify(appUrl)});
    if (u.hostname === 'localhost' || u.hostname === '127.0.0.1') { event.preventDefault(); cb(true); }
    else cb(false);
  });`.trim();
}

/** Builds keyboard shortcut handler for reload/DevTools.
 *  F5/Ctrl+R: hard reload. F12/Ctrl+Shift+I: DevTools. */
export function buildKeyboardShortcuts(): string {
  return `
  // Local keyboard shortcuts (only when window has focus — NOT globalShortcut)
  win.webContents.on('before-input-event', (event, input) => {
    if (input.type !== 'keyDown') return;
    const ctrl = input.control || input.meta;
    // F5 / Ctrl+R / Ctrl+Shift+R — hard reload (bypasses cache)
    if (input.key === 'F5' || (ctrl && input.key.toLowerCase() === 'r')) {
      event.preventDefault();
      win.webContents.reloadIgnoringCache();
    }
    // F12 / Ctrl+Shift+I — toggle DevTools
    if (input.key === 'F12' || (ctrl && input.shift && input.key.toLowerCase() === 'i')) {
      event.preventDefault();
      win.webContents.toggleDevTools();
    }
    // Ctrl+Shift+Delete — clear all caches and hard reload
    if (ctrl && input.shift && input.key === 'Delete') {
      event.preventDefault();
      win.webContents.session.clearCache().then(() => {
        win.webContents.session.clearStorageData().then(() => {
          win.webContents.reloadIgnoringCache();
        });
      });
    }
  });`.trim();
}

/** Window state persistence helpers — loads/saves window bounds to userData */
export const WINDOW_STATE_HELPERS = `
function loadBounds(dw, dh) {
  try {
    const d = JSON.parse(fs.readFileSync(stateFile, 'utf8'));
    if (d.width > 0 && d.height > 0) return d;
  } catch {}
  return { width: dw, height: dh };
}

function saveBounds(win) {
  try { fs.writeFileSync(stateFile, JSON.stringify(win.getBounds())); } catch {}
}
`.trim();
