// `am theme adopt` — take aio's default stylesheet INTO the app, as a file the
// app owns from then on.
//
// The problem it solves is the one case `ui.theme` cannot make safe on its own.
// An app with no CSS can take the framework's look freely (nothing of its own
// to break). An app with its own CSS gets the visual defaults out of the way
// (`ui.theme: "auto"`). But "I like aio's look and want to build ON it" leaves
// the app's appearance depending on a file it does not control and has never
// read — so a framework upgrade can move its UI, silently, with no compile
// error and no test failure. A field app lost half its content pane to
// `:where(main){max-width:72rem}` exactly that way.
//
// Adopting removes the dependency instead of promising to be careful with it:
// the rules become a stylesheet in the app's repo, in its git history, that no
// aio version can touch. It also needs no new switch — an app that has a
// stylesheet is one `ui.theme: "auto"` already steps aside for, so exactly one
// copy of the theme exists and it is the app's.
import { readDenoJson } from "../server/deno-json.ts";
import { join } from "@std/path";
import { appThemeCss } from "../build/app-theme.ts";
import { resolveAppDir } from "../build/build-config.ts";
import { resolveEntryPath } from "../server/paths.ts";
import type { GlobalFlags } from "./am-types.ts";
import { VERSION } from "../server/aio-cli.ts";
import { detectMode, fail, out } from "./am-output.ts";
import { projectRoot } from "./am-project.ts";

const THEME_FILE = "aio-theme.css";
const IMPORT_LINE = `@import "./${THEME_FILE}";`;

/** The header the adopted file carries — what it is, where it came from, and
 *  the one thing that is now true of it: aio will never touch it again. */
function header(appId: string): string {
  return `/* aio's default theme, adopted by this app.
 *
 * Generated by \`am theme adopt\` from aio ${VERSION} for "${appId}".
 * THIS FILE IS YOURS. aio does not read it, will not update it, and no
 * framework upgrade can change what it does — edit it like any other
 * stylesheet.
 *
 * It stays inside \`@layer aio\` on purpose: an unlayered rule in your own CSS
 * beats everything here without !important and without ordering games, so you
 * can override a piece without deleting it.
 *
 * The accent derives from the app's identity — change --aio-accent (or
 * --aio-hue) below and every derived tone follows.
 */
`;
}

/** Resolve the app's identity the same way the running app does: deno.json
 *  `appId`, else its `title`, else the directory name. The accent hue is a hash
 *  of it, so adopting must use the SAME input or the adopted file would come
 *  out a different colour than the app the developer has been looking at. */
function identityOf(cfg: Record<string, unknown>, root: string): string {
  const id = cfg.appId ?? cfg.title;
  if (typeof id === "string" && id.trim()) return id.trim();
  return root.split("/").filter(Boolean).pop() ?? "app";
}

export async function cmdTheme(
  args: string[],
  flags: GlobalFlags,
): Promise<void> {
  // `am theme` is an `am` command like every other one: its refusals are
  // `{"error":…}` on STDOUT under --json, and its result is a document. It used
  // to write console.error + exit(1) — an empty stdout and prose on stderr, so
  // the one contract every scripted caller relies on ("--json always answers
  // with a JSON object") had a hole in it exactly here.
  const mode = detectMode(flags);
  const sub = args[0];
  if (sub !== "adopt") {
    fail(
      `am theme: unknown subcommand ${
        sub ? `"${sub}"` : "(none)"
      } — the only one is:\n` +
        `  am theme adopt    take aio's stylesheet into this app as ${THEME_FILE}\n` +
        `                    (--force overwrites an existing one)`,
      mode,
    );
  }

  // The PROJECT root, not the cwd — one decider (am-project.ts), so
  // `am theme adopt` from `src/` adopts into the app rather than refusing.
  const root = projectRoot();
  // A file that is ABSENT and a file that does not PARSE are different facts,
  // and collapsing them is how a skipped repair still printed "Now run: deno
  // task dev" — the reader throws for the second, naming the file and the
  // reason, and returns null only for the first.
  let found: { config: Record<string, unknown> } | null;
  try {
    found = await readDenoJson(root);
  } catch (e) {
    fail(
      `am theme adopt: ${e instanceof Error ? e.message : String(e)}`,
      mode,
    );
  }
  if (!found) {
    fail(
      `am theme adopt: no deno.json in ${root} — run it from inside the app ` +
        `(any directory under the one holding deno.json).`,
      mode,
    );
  }
  const cfg = found.config;
  // THE app-dir decider: assets live beside the entry, wherever that is. A
  // second rule here would put the stylesheet somewhere the app does not load
  // it from — the exact class of bug the decider exists to prevent.
  const appDir = resolveAppDir(root, resolveEntryPath(cfg));
  const themePath = join(appDir, THEME_FILE);
  const stylePath = join(appDir, "style.css");
  const force = args.includes("--force") || flags.force === true;

  // Never silently overwrite: once adopted, the file is the app's, and the
  // developer's edits are the whole point of having it.
  try {
    await Deno.stat(themePath);
    if (!force) {
      fail(
        `am theme adopt: ${themePath} already exists — it is YOURS now, and ` +
          `overwriting it would discard your edits.\n` +
          `  Keep it, or pass --force to replace it with aio ${VERSION}'s ` +
          `current theme (diff it first: git diff after the run).`,
        mode,
      );
    }
  } catch { /* not there — the normal path */ }

  const appId = identityOf(cfg, root);
  await Deno.writeTextFile(themePath, header(appId) + appThemeCss(appId));

  // The file has to be REACHED, or adopting quietly changes nothing. style.css
  // is the one stylesheet aio links, so the import goes at its top (`@import`
  // must precede every rule, or the browser drops it).
  let styleNote: string;
  let existing = "";
  try {
    existing = await Deno.readTextFile(stylePath);
  } catch { /* no style.css yet */ }
  if (existing.includes(IMPORT_LINE)) {
    styleNote = `style.css already imports it — left alone`;
  } else if (existing.trim() === "") {
    await Deno.writeTextFile(
      stylePath,
      `${IMPORT_LINE}\n\n/* Your rules go below. Anything here beats the ` +
        `adopted theme above\n   (it is layered, yours is not) — no ` +
        `!important needed. */\n`,
    );
    styleNote = `wrote style.css importing it`;
  } else {
    await Deno.writeTextFile(stylePath, `${IMPORT_LINE}\n${existing}`);
    styleNote = `added the @import to the top of style.css`;
  }

  const rel = (p: string) => p.startsWith(root) ? p.slice(root.length + 1) : p;
  out(
    {
      adopted: rel(themePath),
      appId,
      aio: VERSION,
      style: styleNote,
    },
    mode,
    () =>
      `✓ adopted aio ${VERSION}'s theme → ${rel(themePath)}\n` +
      `  ${styleNote}\n` +
      `\n` +
      `  It is a normal stylesheet now: yours to edit, in your git history, ` +
      `and no\n  aio upgrade can change it.\n` +
      `  aio emits no look of its own beside it: the default (\`ui.theme:\n` +
      `  "tokens"\`) paints nothing, and \`"auto"\` steps aside for an app ` +
      `with a\n  stylesheet — so there is exactly one theme and it is this ` +
      `file.`,
  );
}
