// record.ts — `am record`: turn a recorded action journal into a runnable
// bootCells replay test. Reads the durable journal — the one action source that carries method payloads — and
// emits a test skeleton that re-dispatches the flow, ready for assertions.
import type { GlobalFlags } from "./am-types.ts";
import { detectMode, out, outError } from "./am-output.ts";
import {
  defaultJournalPath,
  overwriteRefusal,
  resolveAmAppId,
} from "./am-utils.ts";
// THE sentinel, not a copy of it — one decider for "this payload was
// redacted" across every sink (journal, timeline, am). am → diagnostics is an
// allowed boundary edge.
import { REDACTED } from "../diagnostics/redact.ts";
import { count } from "../diagnostics/fmt.ts";

type Action = { type: string; payload?: unknown; redacted?: true };

/** A journal entry whose arguments the redactor dropped. Nothing downstream can
 *  reproduce it: `am replay` would re-dispatch the literal string
 *  `"[redacted]"` at a running app, and `am record` would emit
 *  `await vault.unlockWith();` — a "runnable replay test" that cannot run. */
export function isRedactedRow(
  r: { payload?: unknown; redacted?: true },
): boolean {
  return r.redacted === true || r.payload === REDACTED;
}

/** Generate a bootCells replay test from recorded actions — pure + unit-tested.
 *  `cell:method` with `{ args }` becomes `await cell.method(...args)`; framework
 *  `__` methods are skipped. Imports are best-effort (`../src/<cell>.ts`) for the
 *  author to adjust; a TODO marks where to assert final state. */
export function generateReplayTest(
  actions: Action[],
  opts: { name?: string; cellDir?: string } = {},
): string {
  const cells = new Set<string>();
  const calls: string[] = [];
  let redactedCount = 0;
  for (const a of actions) {
    const ci = a.type.indexOf(":");
    if (ci < 0) continue; // not a cell:method action
    const cell = a.type.slice(0, ci);
    const method = a.type.slice(ci + 1);
    if (method.startsWith("__")) continue; // framework-internal
    if (isRedactedRow(a)) {
      // Its arguments were never written to disk, so this call CANNOT be
      // reproduced. Emitting `await vault.unlockWith();` produced a test that
      // compiles, runs, and reproduces something other than what happened —
      // the worst of the three options. A commented gap the author has to fill
      // is the honest one.
      redactedCount++;
      cells.add(cell);
      calls.push(
        `  // UNREPRODUCIBLE: ${a.type} was redacted (redactActions) — its ` +
          `arguments\n  // were never recorded. Supply them to continue the ` +
          `flow:\n  // await ${cell}.${method}(/* … */);`,
      );
      continue;
    }
    cells.add(cell);
    const args = (a.payload as { args?: unknown[] })?.args ?? [];
    calls.push(
      `  await ${cell}.${method}(${
        args.map((x) => JSON.stringify(x)).join(", ")
      });`,
    );
  }
  const dir = opts.cellDir ?? "../src";
  const cellList = [...cells];
  const imports = cellList.map((c) => `import { ${c} } from "${dir}/${c}.ts";`);
  const name = opts.name ?? "recorded flow";
  return [
    `// Generated by \`am record\` — replay of ${
      count(
        calls.length - redactedCount,
        "action",
      )
    }.`,
    `// Adjust the cell import paths and add assertions where marked.`,
    ...(redactedCount > 0
      ? [
        `//`,
        `// ⚠ ${
          count(redactedCount, "action")
        } in this flow were REDACTED and could not`,
        `// be generated — their arguments were never recorded. They appear`,
        `// below as commented gaps. This replay is INCOMPLETE until you fill`,
        `// them in.`,
      ]
      : []),
    `import { assertEquals } from "@std/assert";`,
    `import { bootCells } from "aio/testing";`,
    ...imports,
    ``,
    `Deno.test(${JSON.stringify(name)}, async () => {`,
    `  await using h = bootCells([${cellList.join(", ")}]);`,
    ...calls,
    `  await h.settle();`,
    `  // TODO: assert final state, e.g. assertEquals(${
      cellList[0] ?? "cell"
    }.field, expected);`,
    `});`,
    ``,
  ].join("\n");
}

/** One parsed journal line — carries `seq`/`ts` so callers can range-filter. */
export type JournalRow = {
  seq: number;
  type: string;
  payload?: unknown;
  ts?: number;
};

/** Parse a journal file (JSONL: `{seq,type,payload,ts}` per line) into ordered
 *  rows, tolerating a torn final line. Sorted ascending by seq. */
export function parseJournalEntries(text: string): JournalRow[] {
  const rows: JournalRow[] = [];
  for (const line of text.split("\n")) {
    if (!line.trim()) continue;
    try {
      const e = JSON.parse(line) as JournalRow;
      if (typeof e.type === "string") rows.push(e);
    } catch {
      break; // torn tail
    }
  }
  rows.sort((a, b) => (a.seq ?? 0) - (b.seq ?? 0));
  return rows;
}

/** Parse a journal file into ordered `{type,payload}` actions (seq/ts dropped). */
export function parseJournalActions(text: string): Action[] {
  return parseJournalEntries(text).map((r) => ({
    type: r.type,
    payload: r.payload,
  }));
}

/** `am record [out.test.ts] --from <journal>` — generate a replay test from a
 *  recorded journal. `--from` defaults to the app's `<data>/journal`.
 *  Writes to the output path, or prints to stdout. */
export async function cmdRecord(
  args: string[],
  flags: GlobalFlags,
): Promise<void> {
  const mode = detectMode(flags);
  const outPath = args.find((a) => !a.startsWith("--"));
  // A generated test is written over the file at this path. `am backup`
  // refuses to clobber; this did it silently — and the file most likely to be
  // sitting at `tests/foo.test.ts` is the hand-written test it replaces.
  if (outPath) {
    const clobber = overwriteRefusal(
      outPath,
      !!flags.force,
      "a generated replay test",
    );
    if (clobber) {
      outError(clobber, mode);
      Deno.exit(1);
    }
  }
  const fromFlag = args.find((a) => a.startsWith("--from="));
  const journalPath = fromFlag
    ? fromFlag.slice("--from=".length)
    : defaultJournalPath(resolveAmAppId(flags.app));
  let text: string;
  try {
    text = await Deno.readTextFile(journalPath);
  } catch {
    outError(
      `no journal at "${journalPath}" — enable it with aio.run({ journal: true }) ` +
        `or pass --from=<path>`,
      mode,
    );
    Deno.exit(1);
  }
  const actions = parseJournalActions(text);
  if (actions.length === 0) {
    outError(`journal "${journalPath}" has no replayable actions`, mode);
    Deno.exit(1);
  }
  const test = generateReplayTest(actions, {
    name: outPath
      ? outPath.replace(/.*\//, "").replace(/\.test\.ts$/, "")
      : "recorded flow",
  });
  if (outPath) {
    await Deno.writeTextFile(outPath, test);
    out(
      mode === "pretty"
        ? `wrote ${outPath} (${actions.length} actions)`
        : { wrote: outPath, actions: actions.length },
      mode,
    );
  } else {
    out(test, mode);
  }
}
