#!/usr/bin/env -S deno run -A
// Generates src/android-template.ts from android-template/ directory.
// Run after any template change: deno run -A scripts/gen-android-template.ts
import { join, relative, resolve } from "@std/path";

const templateDir = resolve("android-template");
const outputFile = resolve("src/build/android-template.ts");
const SKIP = new Set([".gradle", "build", ".idea"]);

const entries: [string, string][] = [];

async function walk(dir: string): Promise<void> {
  for await (const e of Deno.readDir(dir)) {
    if (SKIP.has(e.name)) continue;
    const full = join(dir, e.name);
    if (e.isDirectory) {
      await walk(full);
      continue;
    }
    const rel = relative(templateDir, full).replaceAll("\\", "/");
    entries.push([rel, await Deno.readTextFile(full)]);
  }
}

await walk(templateDir);
entries.sort((a, b) => a[0].localeCompare(b[0]));

const lines = [
  "// AUTO-GENERATED by scripts/gen-android-template.ts — do not edit manually",
  "// Regenerate: deno run -A scripts/gen-android-template.ts",
  "",
  "export const ANDROID_TEMPLATE: Record<string, string> = {",
  ...entries.map(([path, content]) =>
    `  ${JSON.stringify(path)}: ${JSON.stringify(content)},`
  ),
  "}",
  "",
];

await Deno.writeTextFile(outputFile, lines.join("\n"));
// Format it here, or the next `deno fmt` shows the generated file as a diff and
// the regenerate step looks like it did something it did not.
await new Deno.Command("deno", {
  args: ["fmt", outputFile],
  stdout: "null",
  stderr: "null",
}).output();
console.log(`✓ src/build/android-template.ts — ${entries.length} files`);
