#!/usr/bin/env -S deno run -A
// Same shape as gen-android-template.ts: the checked-in `ios-template/` tree is
// inlined into `src/build/ios-template.ts`, so a compiled `deno task build`
// carries it and never reads the framework checkout at build time.
import { join, relative, resolve } from "@std/path";

const templateDir = resolve("ios-template");
const outputFile = resolve("src/build/ios-template.ts");
const SKIP = new Set(["build", "xcuserdata", ".DS_Store"]);

const entries: [string, string][] = [];

async function walk(dir: string): Promise<void> {
  for await (const e of Deno.readDir(dir)) {
    if (SKIP.has(e.name)) continue;
    const full = join(dir, e.name);
    if (e.isDirectory) {
      await walk(full);
      continue;
    }
    const rel = relative(templateDir, full).replaceAll("\\", "/");
    entries.push([rel, await Deno.readTextFile(full)]);
  }
}

await walk(templateDir);
entries.sort((a, b) => a[0].localeCompare(b[0]));

const lines = [
  "// AUTO-GENERATED by scripts/gen-ios-template.ts — do not edit manually",
  "// Regenerate: deno run -A scripts/gen-ios-template.ts",
  "",
  "export const IOS_TEMPLATE: Record<string, string> = {",
  ...entries.map(([path, content]) =>
    `  ${JSON.stringify(path)}: ${JSON.stringify(content)},`
  ),
  "}",
  "",
];

await Deno.writeTextFile(outputFile, lines.join("\n"));
