// deno-lint-ignore-file
/**
 * @module
 * React entry point — `aio/react`.
 *
 * Single import for all React component needs: hooks, routing, protocol,
 * and server framework symbols.
 *
 * @example
 * ```ts
 * import { useFeature, useLocal, useConnected } from "aio/react";
 * ```
 */

// ── Full React runtime (hooks, routing, protocol) ────────────────────
export * from "./browser.ts";

// ── Server/framework symbols NOT already in browser.ts ───────────────
export {
  bindFeature,
  call,
  composeFeatures,
  composeMiddleware,
  connectCli,
  connectCliUDS,
  createDB,
  createSelector,
  createSliceSelector,
  deepFreeze,
  DEFAULT_PRAGMAS,
  draft,
  instances,
  integer,
  lint,
  markAsync,
  matchEffect,
  parseCli,
  pk,
  real,
  ref,
  resolveAppId,
  table,
  testFeature,
  text,
  VERSION,
} from "../mod.ts";

// ── Server/framework types (none conflict with browser.ts) ────────────
export type {
  ActionsFeatureConfig,
  ActionSource,
  ActionUnion,
  AioApp,
  AioConfig,
  AioError,
  AioErrorCode,
  AioErrorContext,
  AioErrorSource,
  AioMeta,
  AioUser,
  AsyncMethod,
  CallOptions,
  Catalog,
  CheckpointData,
  CircuitBreakerConfig,
  CliApp,
  CliFlags,
  ColumnDef,
  ColumnOpts,
  ComposedFeatures,
  Creators,
  DB,
  DBOpts,
  DiagEvent,
  DiagEventDetail,
  DiagnosticsConfig,
  DiagnosticsOptions,
  DirectCalling,
  ExecuteHandlers,
  ExtractState,
  FactoryCreators,
  FactoryResult,
  FeatureAio,
  FeatureDef,
  FeatureEntry,
  FeatureExecuteFn,
  FeatureMethods,
  FeatureReduceFn,
  FeaturesConfig,
  FeatureStateSize,
  FeatureStatus,
  FlatActions,
  FlowDef,
  FlowStep,
  FlowStepRecord,
  Gen,
  GenCtx,
  InstanceInfo,
  LayerThreshold,
  Lint,
  LockData,
  Log,
  LogConfig,
  LogLevel,
  LowerFirst,
  MachineConfig,
  MemoryConfig,
  MemoryReport,
  Method,
  MethodsFeatureConfig,
  MiddlewareFn,
  Msg,
  PerfBudget,
  PerfCheck,
  Prefixed,
  QueryOpts,
  QueryResult,
  ReduceBreakdown,
  ReduceHandlers,
  RenderBudget,
  ScheduleDef,
  ScheduleEffect,
  ScopedApp,
  Selector,
  SendOf,
  SingletonMode,
  SyncMethod,
  TableDef,
  TestContext,
  Tx,
  TypedCreator,
  UiConfig,
  VitalAlert,
  VitalHint,
  VitalLayer,
  VitalsConfig,
  VitalStatus,
  VitalThresholds,
  WhereClause,
  WhereOp,
} from "../mod.ts";
